server:
  port: 8090
  
spring:
  application:
    name: customer
  data:
    mongodb:
      uri: mongodb://localhost:27017/customer
      
topic:
  groupid: customer-consumer
  purchase:
    names: purchase-topic